import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ToastContainer } from 'react-toastify';
import { Footer } from '@/components/Footer';
import "react-toastify/dist/ReactToastify.css";
import { SidebarComp } from '@/components/SidebarComp';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark text-neutral-200`}>
        <SidebarComp>
          <div className='p-5'>
          {children}
          </div>
          <Footer/>
        </SidebarComp>
        <ToastContainer
          position="bottom-right"
          autoClose={3000}
          closeOnClick
          draggable
        />
      </body>
    </html>
  );
}
